line-length = 79

lint.select = ["ALL"]

lint.ignore = [
    "D203",  # 1 blank line required before class docstring
    "D205",  # 1 blank line required between summary line and description
    "D213",  # incompatible. Ignoring `multi-line-summary-second-line`
    "TRY003",  # Avoid specifying long messages outside the exception class
]

[lint.extend-per-file-ignores]
"docs/source/conf.py" = [
  "A001",  # builtin-variable-shadowing
  "D100",  # Missing docstring in public module
  "E402",  # Module level import not at top of file
  "ERA001",  # Found commented-out code
  "ERA001",  # Found commented-out code
  "EXE001",  # Shebang is present but file is not executable
]
"test_*.py" = [
    "ANN001",  # Missing type annotation for function argument
    "ANN201",  # Missing return type annotation for public function
    "ANN202",  # Missing return type annotation for private function
    "INP001",  # File is part of an implicit namespace package
    "PD901",  # Avoid using the generic variable name `df` for DataFrames
    "S101",  # Use of assert detected
]
# nbqa-ruff acts on converted .py so we cannot glob .ipynb :-/
# https://github.com/nbQA-dev/nbQA/issues/823
"notebooks/*" = [
    "ANN001",  # Missing type annotation for function argument
    "ANN201",  # Missing return type annotation for public function
    "B018",  # Found useless expression. Either assign it to a variable or remove it
    "D100",  # Missing docstring in public module
    "D103",  # Missing docstring in public function
    "E402",  # Module level import not at top of file
    "FBT003",  # Boolean positional value in function call
    "INP001",  # File is part of an implicit namespace package
    "PD901",  # Avoid using the generic variable name `df` for DataFrames
    "T201",  # `print` found"
]
[lint.pycodestyle]
max-doc-length = 180
