name: Full Tests

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]
        os: [ ubuntu-latest ]
        include:
          - os: windows-latest
            python-version: "3.14"
          - os: macos-latest
            python-version: "3.14"
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Micromamba Python ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
      with:
        # Remove the line below when micromamba 2.6.2 is released.
        micromamba-version: '2.6.0-0'
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=${{ matrix.python-version }}
          --file requirements.txt
          --file requirements-dev.txt
          --channel conda-forge

    - name: Install library
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Full Tests
      # Use the --record-mode=rewrite if you need to re-record the cassetts.
      run: >
        pushd tests && python download_test_data.py && popd
        && python -m pytest -rxs --cov=erddapy tests
