name: Full Tests

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.11", "3.14" ]
        os: [ ubuntu-latest ]
        include:
          - os: windows-latest
            python-version: "3.14"
          - os: macos-latest
            python-version: "3.14"
          - os: macos-15-intel
            python-version: "3.14"
      fail-fast: false
    permissions:
      actions: none

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Install erddapy
      run: |
        pip install -e ".[dev,extras,docs]"

    - name: Full Tests
      # Use the --record-mode=rewrite if you need to re-record the cassetts.
      run: >
        pushd tests && python download_test_data.py && popd
        && python -m pytest -rxs tests
